/*
 * \file PmsmFoc_Interface.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "PmsmFoc_Interface.h"
#include "PmsmFoc_Functions.h"
#include "PmsmFoc_Gatedriver.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

void PmsmFoc_Interface_startMotor(MOTORCTRL_S* const motorCtrl)
{
	if(motorCtrl->interface.CurrnetIfMode == STOP_MODE)
	{
		motorCtrl->interface.CurrnetIfMode = RUNNING_MODE;
		motorCtrl->CtrlParms.state = STATE_focClosedLoop;
		#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
		PmsmFoc_speedcontrol_enable(&motorCtrl->pmsmFoc.speedControl);
		PmsmFoc_Interface_setStartTargetSpeed(motorCtrl);
		#endif
		PmsmFoc_Gatedriver_Enable();
	}
}

void PmsmFoc_Interface_calMotor(MOTORCTRL_S* const motorCtrl)
{
	if(motorCtrl->interface.CurrnetIfMode == STOP_MODE)
	{
		motorCtrl->interface.CurrnetIfMode = CAL_MODE;
		motorCtrl->CtrlParms.state = STATE_PhaseCalibration;
		PmsmFoc_PhaseCurrentSense_resetCalibrationStatus(&motorCtrl->inverter.phaseCurrentSense);
	#if(POSITION_SENSOR_TYPE == ENCODER)
		PmsmFoc_PositionAcquisition_init(&motorCtrl->positionSensor, PositionAcquisition_SensorType_Encoder);
		/* Reset the encoder calibration status */
		PmsmFoc_resetEncoderCalibrationStatus(motorCtrl);
	#else
		/* For other position sensor */
	#endif
		#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
		PmsmFoc_speedcontrol_disable(&motorCtrl->pmsmFoc.speedControl);
		#endif
		PmsmFoc_Gatedriver_Enable();
	}
}

void PmsmFoc_Interface_stopMotor(MOTORCTRL_S* motorCtrl)
{
	if((motorCtrl->interface.CurrnetIfMode == RUNNING_MODE)||(motorCtrl->interface.CurrnetIfMode == DEMO_MODE))
	{
		motorCtrl->interface.CurrnetIfMode = STOPPING_MODE;
		motorCtrl->pmsmFoc.modulationIndex.real = 0;
		motorCtrl->pmsmFoc.modulationIndex.imag = 0;
		PmsmFoc_SvmStart(&motorCtrl->inverter, motorCtrl->pmsmFoc.modulationIndex);
		#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
		/* For the fast stop response */
		Ifx_RampF32_setSlewRate(&motorCtrl->pmsmFoc.speedRamp,USER_MOTOR_SPEED_RAMP_SLEW_RATE*4,USER_MOTOR_SPEED_RAMP_PERIOD);
		PmsmFoc_Interface_setStopMotorTargetSpeed(motorCtrl);
		#endif
		#if(POSITION_SENSOR_TYPE == ENCODER)
		/* measSpeed returns the wrong value even motor stopped */
		motorCtrl->positionSensor.encoder.incrEncoder.speedFilterEnabled = 0;
		#endif
	}
	else if(motorCtrl->pmsmFoc.speedControl.measSpeed == 0 && motorCtrl->interface.CurrnetIfMode == STOPPING_MODE)
	{
		motorCtrl->interface.CurrnetIfMode = STOP_MODE;
		motorCtrl->CtrlParms.state = STATE_motorStop;
		#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
		Ifx_RampF32_setSlewRate(&motorCtrl->pmsmFoc.speedRamp,USER_MOTOR_SPEED_RAMP_SLEW_RATE,USER_MOTOR_SPEED_RAMP_PERIOD);
		#endif
		PmsmFoc_SvmStop(&motorCtrl->inverter);
		PmsmFoc_Gatedriver_Disable();
		#if(POSITION_SENSOR_TYPE == ENCODER)
		motorCtrl->positionSensor.encoder.incrEncoder.speedFilterEnabled = 1;
		#endif
	}
}
#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
void PmsmFoc_Interface_setDemo(MOTORCTRL_S* const motorCtrl)
{
	if(motorCtrl->interface.CurrnetIfMode == STOP_MODE)
	{
		uint16 democnt;
		motorCtrl->interface.CurrnetIfMode = DEMO_MODE;
		motorCtrl->CtrlParms.state         = STATE_demo;
		democnt                            = motorCtrl->democontrol.scenarioCnt;
		PmsmFoc_Interface_setMotorTargetSpeed(motorCtrl,motorCtrl->democontrol.demospeed[democnt][0]);
		PmsmFoc_speedcontrol_enable(&motorCtrl->pmsmFoc.speedControl);
		PmsmFoc_Gatedriver_Enable();
	}
}
#endif
void PmsmFoc_Interface_setOpenlooptest(MOTORCTRL_S* const motorCtrl)
{
	if(motorCtrl->interface.CurrnetIfMode == STOP_MODE)
	{
		motorCtrl->interface.CurrnetIfMode       = RUNNING_MODE;
		motorCtrl->CtrlParms.state               = STATE_vfOpenLoop;
		motorCtrl->openLoop.electricalAngle      = 0;
		motorCtrl->openLoop.electricalAngleDelta = 1;
		motorCtrl->openLoop.modulationIndex.real = 0;
		motorCtrl->openLoop.modulationIndex.imag = 0;
		motorCtrl->openLoop.amplitude            = USER_MOTOR_ENCODER_CAL_TOP_ZERO_AMPL_MAX;
		PmsmFoc_Gatedriver_Enable();
	}
}

void PmsmFoc_Interface_brakeMotor(MOTORCTRL_S* const motorCtrl)
{

}

void PmsmFoc_Interface_vfOpenLoopRampup(MOTORCTRL_S* const motorCtrl)
{

}

void PmsmFoc_Interface_disableInverter(MOTORCTRL_S* const motorCtrl)
{

}

void PmsmFoc_Interface_enableInverter(MOTORCTRL_S* const motorCtrl)
{

}


void PmsmFoc_Interface_geVdcLink(MOTORCTRL_S* const motorCtrl)
{

}

boolean PmsmFoc_Interface_setMotorTargetSpeed(MOTORCTRL_S* motorCtrl, float32 motorTargetSpeed)
{	
	float32 maxSpeed = PmsmFoc_speedcontrol_getMaxSpeed(&motorCtrl->pmsmFoc.speedControl);
	float32 minSpeed = PmsmFoc_speedcontrol_getMinSpeed(&motorCtrl->pmsmFoc.speedControl);

	boolean result;
    if ((__absf(motorTargetSpeed)) > (maxSpeed))
    {
        motorCtrl->interface.motorTargetSpeed = maxSpeed;
        result = FALSE;
    }
    else if ((__absf(motorTargetSpeed)) < (minSpeed))
    {
        motorCtrl->interface.motorTargetSpeed = minSpeed;
        result = FALSE;
    }
    else
    {
        motorCtrl->interface.motorTargetSpeed = motorTargetSpeed;
        result = TRUE;
    }
    return result;
}

boolean PmsmFoc_Interface_plsMotorTargetSpeed(MOTORCTRL_S* motorCtrl)
{	
	boolean result = FALSE;
	if(motorCtrl->interface.CurrnetIfMode == RUNNING_MODE)
	{
		float32 maxSpeed = PmsmFoc_speedcontrol_getMaxSpeed(&motorCtrl->pmsmFoc.speedControl);
		float32	refSpeed = PmsmFoc_speedcontrol_getRefSpeed(&g_motorCtrl.pmsmFoc.speedControl);
		float32 motorTargetSpeed;
		motorTargetSpeed = refSpeed +100.0f;

		if ((__absf(motorTargetSpeed)) > (maxSpeed))
		{
			motorCtrl->interface.motorTargetSpeed = maxSpeed;
			result = FALSE;
		}
		else
		{
			motorCtrl->interface.motorTargetSpeed = motorTargetSpeed;
			result = TRUE;
		}
	}
    return result;
}

boolean PmsmFoc_Interface_mnsMotorTargetSpeed(MOTORCTRL_S* motorCtrl)
{	
	boolean result = FALSE;
	if(motorCtrl->interface.CurrnetIfMode == RUNNING_MODE)
	{
		float32 minSpeed = PmsmFoc_speedcontrol_getMinSpeed(&motorCtrl->pmsmFoc.speedControl);
		float32	refSpeed = PmsmFoc_speedcontrol_getRefSpeed(&g_motorCtrl.pmsmFoc.speedControl);
		float32 motorTargetSpeed;
		motorTargetSpeed = refSpeed - 100.0f;

		if ((__absf(motorTargetSpeed)) < (minSpeed))
		{
			motorCtrl->interface.motorTargetSpeed = minSpeed;
			result = FALSE;
		}
		else
		{
			motorCtrl->interface.motorTargetSpeed = motorTargetSpeed;
			result = TRUE;
		}
	}
    return result;
}

boolean PmsmFoc_Interface_setStartTargetSpeed(MOTORCTRL_S* motorCtrl)
{	
	float32 minSpeed = PmsmFoc_speedcontrol_getMinSpeed(&motorCtrl->pmsmFoc.speedControl);
	boolean result;
	motorCtrl->interface.motorTargetSpeed = minSpeed;
	result = TRUE;
    return result;
}

boolean PmsmFoc_Interface_setStopMotorTargetSpeed(MOTORCTRL_S* motorCtrl)
{
    boolean result;
	motorCtrl->interface.motorTargetSpeed = 0;
	result = TRUE;
    return result;
}
