/*
 * \file PmsmFoc_StateMachine.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_StateMachine.h"
#include "PmsmFoc_Gatedriver.h"
#include "Cpu/Std/IfxCpu.h"
#include "Misc_Init.h"
#include "PmsmFoc_Interface.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

float32 downspeed;
float32 upspeed;
void PmsmFoc_StateMacine_doControlLoop(MOTORCTRL_S* const motorCtrl)
{
	switch (motorCtrl->CtrlParms.state)
	{
	case STATE_PhaseCalibration:
		/* As soon as Adc initialization, ADC triggers the StateMacine */
		/* Calibration can progress when initializing process is complete and after the gate driver or motor is stabilized */
		if(motorCtrl->CtrlParms.initState == INIT_DONE && motorCtrl->inverter.phaseCurrentSense.calibration.calwait>20)
		{
			if(motorCtrl->inverter.phaseCurrentSense.calibration.status == PmsmFoc_SensorAdc_CalibrationStatus_notDone)
			{
				PmsmFoc_PhaseCurrentSense_getRawPhaseCurrentValues(&motorCtrl->inverter.phaseCurrentSense);
				PmsmFoc_PhaseCurrentSense_doCalibration(&motorCtrl->inverter.phaseCurrentSense);
			}
			else
			{
			#if(POSITION_SENSOR_TYPE == ENCODER)
				motorCtrl->CtrlParms.state = STATE_PositionCalibration;
			#else
				motorCtrl->CtrlParms.state = STATE_motorStop;
				PmsmFoc_SvmStop(&motorCtrl->inverter);
				PmsmFoc_Gatedriver_Disable();
			#endif
			}

		}
		break;
	case STATE_PositionCalibration:
		PmsmFoc_doEncoderCalibration(motorCtrl);
		if(motorCtrl->positionSensor.encoder.calibrationStatus == ENC_CAL_DONE)
		{
			motorCtrl->CtrlParms.state = STATE_motorStop;
			PmsmFoc_SvmStop(&motorCtrl->inverter);
			PmsmFoc_Gatedriver_Disable();
		}
		break;
	case STATE_focClosedLoop:
		PmsmFoc_doFieldOrientedControl(motorCtrl);
		break;
	case STATE_tuneCurrentRegulators:
		/* Not used*/
		PmsmFoc_tuneCurrentRegulator(motorCtrl);
		break;
	case STATE_prePositioning:
		/* Not used*/
		break;
	case STATE_motorStop:
		PmsmFoc_PhaseCurrentSense_getRawPhaseCurrentValues(&motorCtrl->inverter.phaseCurrentSense);
	/* To avoid the backward roatation measSpeed value*/
	/* Update electrical position and measSpeed*/
	motorCtrl->pmsmFoc.electricalAngle =
			(sint16) PmsmFoc_PositionAcquisition_updatePosition(&motorCtrl->positionSensor);
		break;
	case STATE_motorIdle:
		/* Not used*/
		break;
	case STATE_vfOpenLoop:
		PmsmFoc_doVfControl(motorCtrl);
		break;
	case STATE_enableInverter:
		/* Not used*/
		break;
	case STATE_demo:
	#if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
		PmsmFoc_doDemo(motorCtrl);
	#endif
		break;
	default:
		break;
	}

}






