/*
 * \file PmsmFoc_Interrupts.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_Interrupts.h"
#if(TLF35584_DRIVER == ENABLED)
	#include "TLF3xx8x.h"
#endif /* End of TLF35584_DRIVER*/

#if(TLE9180_DRIVER == ENABLED)
#include "TLE9180.h"
#endif /* End of TLE9180_DRIVER*/

#if(ONE_EYEMODE == ENABLED)
	#include "OneEye_Init.h"
#endif /* End of ONE_EYEMODE*/
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
/** \brief Interrupt service unit for EVADC, end of EVADC conversion call back
 *
 */
IFX_INTERRUPT(PmsmFoc_Evadc_PhaseCurSense_Isr, 0, INTERRUPT_PRIORITY_EVADC_CUR)
{
	PmsmFoc_StateMacine_doControlLoop(&g_motorControl);
#if(ONE_EYEMODE == ENABLED)
	OneEye_osciStep();
#endif /* End of ONE_EYEMODE*/
}

#if(INVERTERCARD_TYPE == EMOTOR_DRIVE_V_3_1)
	#if(PHASE_CURRENT_RECONSTRUCTION == USER_LOWSIDE_THREE_SHUNT_WITH_HIGHSIDE_MONITORING)
	/** \brief Interrupt service unit for EVADC, end of EVADC conversion call back
	 *
	*/
	/* STEVE:INTERRUPT_PRIORITY_EVADC_HSCUR is not used */
	IFX_INTERRUPT(PmsmFoc_Evadc_CurrentDCLinkSenseHs_Isr, 0, INTERRUPT_PRIORITY_EVADC_HSCUR)
	{
		PmsmFoc_CurrentDCLinkSenseHs_getRawCurrentValue(&g_motorControl.inverter.highSideCurrentSense);
	}
	#endif
	#if(BEMF_MEASUREMENT == ENABLED)
	/** \brief Interrupt service unit for EVADC, end of EVADC conversion call back
	 *
	 */

	IFX_INTERRUPT(PmsmFoc_Evadc_BemfVoltageSense_Isr, 0, INTERRUPT_PRIORITY_EVADC_VBEMF)
	{
		PmsmFoc_BemfVoltageSense_getValue(&g_motorControl.inverter.bemfVoltageSense);
	}
	#endif
	#if(DC_LINK_VOLTAGE_MEASUREMENT == ENABLED)
	/** \brief Interrupt service unit for EVADC, end of EVADC conversion call back
	 *
	 */
	IFX_INTERRUPT(PmsmFoc_Evadc_DcLinkVoltageSense_Isr, 0, INTERRUPT_PRIORITY_EVADC_VDCL)
	{
		PmsmFoc_DcLinkVoltageSense_getValue(&g_motorControl.inverter.dcLinkVoltageSense);
	}
	#endif
#endif /* End of (INVERTERCARD_TYPE == EMOTOR_DRIVE_V_3_1) */

#if(POSITION_SENSOR_TYPE == ENCODER)
/** \brief Interrupt service unit for GPT12 Zero position event
 *
 */
IFX_INTERRUPT(PmsmFoc_Gpt12_Encoder_TzIsr, 0, INTERRUPT_PRIORITY_ENCODER_GPT12)
{
	IfxGpt12_IncrEnc_onZeroIrq(&g_motorControl.positionSensor.encoder.incrEncoder);
}
#endif
#if(TLF35584_DRIVER == ENABLED)
/** \brief Handle tlf_qspi_Tx interrupt.
 *
 * \isrProvider \ref CPU_WHICH_SERVICE_TLF
 * \isrPriority \ref ISR_PRIORITY_TLF_QSPI
 *
 */
IFX_INTERRUPT(ISR_tlf_qspi_Tx, CPU_WHICH_SERVICE_TLF, ISR_PRIORITY_TLF_QSPI_TX)
{
    IfxCpu_enableInterrupts();
#ifdef TLF_USE_DMA
    IfxQspi_SpiMaster_isrDmaTransmit(&(g_Qspi_TLF_Cpu.drivers.spiMaster));
#else
    IfxQspi_SpiMaster_isrTransmit(&(g_Qspi_TLF_Cpu.drivers.spiMaster));
#endif

}


/** \brief Handle tlf_qspi_Rx interrupt.
 *
 * \isrProvider \ref CPU_WHICH_SERVICE_TLF
 * \isrPriority \ref ISR_PRIORITY_TLF_QSPI
 *
 */
IFX_INTERRUPT(ISR_tlf_qspi_Rx, CPU_WHICH_SERVICE_TLF, ISR_PRIORITY_TLF_QSPI_RX)
{
    IfxCpu_enableInterrupts();
#ifdef TLF_USE_DMA
    IfxQspi_SpiMaster_isrDmaReceive(&(g_Qspi_TLF_Cpu.drivers.spiMaster));
#else
    IfxQspi_SpiMaster_isrReceive(&(g_Qspi_TLF_Cpu.drivers.spiMaster));
#endif
}

/** \brief Handle tlf_qspi_Er interrupt.
 *
 * \isrProvider \ref CPU_WHICH_SERVICE_TLF
 * \isrPriority \ref ISR_PRIORITY_TLF_QSPI
 *
 */
IFX_INTERRUPT(ISR_tlf_qspi_Er, CPU_WHICH_SERVICE_TLF, ISR_PRIORITY_TLF_QSPI_ER)
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrError(&(g_Qspi_TLF_Cpu.drivers.spiMaster));
}
#endif /* End of TLF35584_DRIVER */

#if(TLE9180_DRIVER == ENABLED)
	#if (INTERRUPT_PRIORITY_QSPI4_TX > 0)
	/** \brief Interrupt service units for QSPI4 Transmit
	 *
	 */
	IFX_INTERRUPT(PmsmFoc_Qspi_Tle9180_TxIsr, 0, INTERRUPT_PRIORITY_QSPI4_TX)
	{
		IfxCpu_enableInterrupts();
	#if (SPI_4_USE_DMA == TRUE)
		IfxQspi_SpiMaster_isrDmaTransmit(&g_Qspi_TLE9180_Cpu.drivers.spiMaster);
	#else
		IfxQspi_SpiMaster_isrTransmit(&g_Qspi_TLE9180_Cpu.drivers.spiMaster);
	#endif
	}
	#endif //(INTERRUPT_PRIORITY_QSPI4_TX > 0)

	#if (INTERRUPT_PRIORITY_QSPI4_RX > 0)
	/** \brief Interrupt service units for QSPI4 Receive
	 *
	 */
	IFX_INTERRUPT(PmsmFoc_Qspi_Tle9180_RxIsr, 0, INTERRUPT_PRIORITY_QSPI4_RX)
	{
		IfxCpu_enableInterrupts();
	#if (SPI_4_USE_DMA == TRUE)
		IfxQspi_SpiMaster_isrDmaReceive(&g_Qspi_TLE9180_Cpu.drivers.spiMaster);
	#else
		IfxQspi_SpiMaster_isrReceive(&g_Qspi_TLE9180_Cpu.drivers.spiMaster);
	#endif
	}
	#endif //(INTERRUPT_PRIORITY_QSPI4_RX > 0)

	#if (INTERRUPT_PRIORITY_QSPI4_ERR > 0)
	/** \brief Interrupt service units for QSPI4 Error
	 *
	 */
	IFX_INTERRUPT(PmsmFoc_Qspi_Tle9180_ErrIsr, 0, INTERRUPT_PRIORITY_QSPI4_ERR)
	{
		IfxCpu_enableInterrupts();
		IfxQspi_SpiMaster_isrError(&g_Qspi_TLE9180_Cpu.drivers.spiMaster);
	}
	#endif //(INTERRUPT_PRIORITY_QSPI4_ERR > 0)
#endif /* End of TLE9180_DRIVER */