/**
 * \file IfxStdIf_DPipe.c
 * \brief Standard interface: Data Pipe
 * \ingroup IfxStdIf
 *
 * \copyright Copyright (c) 2013 Infineon Technologies AG. All rights reserved.
 *
 * $Date: 2014-02-27 20:08:23 GMT$
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#include "IfxStdIf_DPipe.h"
#include "Bsp.h"
#include "_Utilities/Ifx_Assert.h"

#include <string.h>
#include <stdio.h>
#include <stdarg.h>

void IfxStdIf_DPipe_print(IfxStdIf_DPipe *stdIf, pchar format, ...)
{
    va_list   args;
    va_start(args, format);
    IfxStdIf_DPipe_printVA(stdIf, format, args);
    va_end(args);
}

void IfxStdIf_DPipe_printVA(IfxStdIf_DPipe *stdIf, pchar format, va_list args)
{
    if (!IfxStdIf_DPipe_isTxDisabled(stdIf))
    {
        char      message[STDIF_DPIPE_MAX_PRINT_SIZE + 1];
        Ifx_SizeT count;
        vsprintf((char *)message, format, args);
        count = (Ifx_SizeT)strlen(message);
        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, count < STDIF_DPIPE_MAX_PRINT_SIZE);
        IfxStdIf_DPipe_write(stdIf, (void *)message, &count, stdIf->writeTimeout);
    }
}


void IfxStdIf_DPipe_writeText(IfxStdIf_DPipe *stdIf, pchar text)
{
    if (!IfxStdIf_DPipe_isTxDisabled(stdIf))
    {
        Ifx_SizeT count;
        count = (Ifx_SizeT)strlen(text);
        IfxStdIf_DPipe_write(stdIf, (void *)text, &count, stdIf->writeTimeout);
    }
}



boolean IfxStdIf_DPipe_nopWrite(IfxStdIf_DPipe *stdIf, void *data, Ifx_SizeT *count, Ifx_TickTime timeout)
{
	IFX_UNUSED_PARAMETER(stdIf);
	IFX_UNUSED_PARAMETER(data);
	IFX_UNUSED_PARAMETER(count);
	IFX_UNUSED_PARAMETER(timeout);
    return FALSE;
}


boolean IfxStdIf_DPipe_nopRead(IfxStdIf_DPipe *stdIf, void *data, Ifx_SizeT *count, Ifx_TickTime timeout)
{
	IFX_UNUSED_PARAMETER(stdIf);
	IFX_UNUSED_PARAMETER(data);
	IFX_UNUSED_PARAMETER(count);
	IFX_UNUSED_PARAMETER(timeout);
    return FALSE;
}


sint32 IfxStdIf_DPipe_nopGetReadCount(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return 0;
}


 sint32 IfxStdIf_DPipe_nopGetWriteCount(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return 0;
}


boolean IfxStdIf_DPipe_nopCanReadCount(IfxStdIf_DPipe *stdIf, Ifx_SizeT count, Ifx_TickTime timeout)
{
	IFX_UNUSED_PARAMETER(stdIf);
	IFX_UNUSED_PARAMETER(count);
	IFX_UNUSED_PARAMETER(timeout);
    return FALSE;
}


 boolean IfxStdIf_DPipe_nopCanWriteCount(IfxStdIf_DPipe *stdIf, Ifx_SizeT count, Ifx_TickTime timeout)
{
	IFX_UNUSED_PARAMETER(stdIf);
	IFX_UNUSED_PARAMETER(count);
	IFX_UNUSED_PARAMETER(timeout);
    return FALSE;
}


IfxStdIf_DPipe_ReadEvent IfxStdIf_DPipe_nopGetReadEvent(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return FALSE;
}


IfxStdIf_DPipe_WriteEvent IfxStdIf_DPipe_nopGetWriteEvent(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return FALSE;
}


boolean IfxStdIf_DPipe_nopFlushTx(IfxStdIf_DPipe *stdIf, Ifx_TickTime timeout)
{
	IFX_UNUSED_PARAMETER(stdIf);
	IFX_UNUSED_PARAMETER(timeout);
	return TRUE;
}


void IfxStdIf_DPipe_nopClearTx(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


void IfxStdIf_DPipe_nopClearRx(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


void IfxStdIf_DPipe_nopOnReceive(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


void IfxStdIf_DPipe_nopOnTransmit(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


void IfxStdIf_DPipe_nopOnError(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


uint32 IfxStdIf_DPipe_nopGetSendCount(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return 0;
}


Ifx_TickTime IfxStdIf_DPipe_nopGetTxTimeStamp(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
    return TIME_NULL;
}


void IfxStdIf_DPipe_nopResetSendCount(IfxStdIf_DPipe *stdIf)
{
	IFX_UNUSED_PARAMETER(stdIf);
}


void IfxStdIf_DPipe_initStdIf(IfxStdIf_DPipe *stdIf)
{
    stdIf->driver = NULL_PTR;
    stdIf->txDisabled = FALSE;
    stdIf->writeTimeout = IFX_CFG_STDIF_DPIPE_TIMEOUT;

    /* *INDENT-OFF* */
    stdIf->write                   = (IfxStdIf_DPipe_Write         )&IfxStdIf_DPipe_nopWrite               ;
    stdIf->read                    = (IfxStdIf_DPipe_Read          )&IfxStdIf_DPipe_nopRead                ;
    stdIf->getReadCount            = (IfxStdIf_DPipe_GetReadCount  )&IfxStdIf_DPipe_nopGetReadCount        ;
    stdIf->getReadEvent            = (IfxStdIf_DPipe_GetReadEvent  )&IfxStdIf_DPipe_nopGetReadEvent        ;
    stdIf->getWriteCount           = (IfxStdIf_DPipe_GetWriteCount )&IfxStdIf_DPipe_nopGetWriteCount       ;
    stdIf->getWriteEvent           = (IfxStdIf_DPipe_GetWriteEvent )&IfxStdIf_DPipe_nopGetWriteEvent       ;
    stdIf->canReadCount            = (IfxStdIf_DPipe_CanReadCount  )&IfxStdIf_DPipe_nopCanReadCount        ;
    stdIf->canWriteCount           = (IfxStdIf_DPipe_CanWriteCount )&IfxStdIf_DPipe_nopCanWriteCount       ;
    stdIf->flushTx                 = (IfxStdIf_DPipe_FlushTx       )&IfxStdIf_DPipe_nopFlushTx             ;
    stdIf->clearTx                 = (IfxStdIf_DPipe_ClearTx       )&IfxStdIf_DPipe_nopClearTx             ;
    stdIf->clearRx                 = (IfxStdIf_DPipe_ClearRx       )&IfxStdIf_DPipe_nopClearRx             ;
    stdIf->onReceive               = (IfxStdIf_DPipe_OnReceive     )&IfxStdIf_DPipe_nopOnReceive           ;
    stdIf->onTransmit              = (IfxStdIf_DPipe_OnTransmit    )&IfxStdIf_DPipe_nopOnTransmit          ;
    stdIf->onError                 = (IfxStdIf_DPipe_OnError       )&IfxStdIf_DPipe_nopOnError             ;
    stdIf->getSendCount            = (IfxStdIf_DPipe_GetSendCount  )&IfxStdIf_DPipe_nopGetSendCount        ;
    stdIf->getTxTimeStamp          = (IfxStdIf_DPipe_GetTxTimeStamp)&IfxStdIf_DPipe_nopGetTxTimeStamp      ;
    stdIf->resetSendCount          = (IfxStdIf_DPipe_ResetSendCount)&IfxStdIf_DPipe_nopResetSendCount      ;
    /* *INDENT-ON* */
}
