/**
 * \file TLE9180_Init.c
 * \brief Initialization of TLE9180 ASIC.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "PmsmFoc_InitTLE9180.h"
#include "IfxPort_PinMap.h"
#include "bsp.h"
 #if(TLE9180_DRIVER == ENABLED)
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
/*STEVE: define error TLE9180*/
TLE9180_CONTROL_ST Tle9180Ctrl;
static void PmsmFoc_Tle9180_InitSpiChannel(void);
/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
/*STEVE: define error TLE9180*/
IfxQspi_SpiMaster           spiMasterQspi4;

/** \brief Initialize QSPI4 Module
 *
 */
void PmsmFoc_TLE9180_InitQspiModule(void)
{
	/* create SPI4 module config */
	IfxQspi_SpiMaster_Config        spiConfig;
	IfxQspi_SpiMaster_initModuleConfig(&spiConfig, &TLE9180_SPI_MODULE);

	/* pin configuration */
	const IfxQspi_SpiMaster_Pins spiPins = 
	{
		&TLE9180_SPI_CLOCK_PIN,  IfxPort_OutputMode_pushPull,
		&TLE9180_SPI_MOSI_PIN,  IfxPort_OutputMode_pushPull,
		&TLE9180_SPI_MISO_PIN,  IfxPort_InputMode_pullDown,
		IfxPort_PadDriver_cmosAutomotiveSpeed1
	};

	/* set the maximum baudrate */
	spiConfig.base.maximumBaudrate = 50.0e6;

	/* ISR priorities and interrupt target */
	spiConfig.base.txPriority  = INTERRUPT_PRIORITY_QSPI4_TX;
	spiConfig.base.rxPriority  = INTERRUPT_PRIORITY_QSPI4_RX;
	spiConfig.base.erPriority  = INTERRUPT_PRIORITY_QSPI4_ERR;
	spiConfig.base.isrProvider = TLE9180_SPI_HOST_CPU;
#if (SPI_4_USE_DMA == TRUE)
	spiConfig.dma.txDmaChannelId = TLE9180_SPI_TX_DMA_CH;
	spiConfig.dma.rxDmaChannelId = TLE9180_SPI_RX_DMA_CH;
	spiConfig.dma.useDma         = TRUE;
#endif
	spiConfig.pins = &spiPins;

	/* initialize module */
	IfxQspi_SpiMaster_initModule(&spiMasterQspi4, &spiConfig);
}

static void PmsmFoc_Tle9180_InitSpiChannel(void)
// Configure SPI Channels for Motor Control Module
{   // Configuration for TLE9180 communication
	/* create channel config */
	IfxQspi_SpiMaster_ChannelConfig spiChConfig;
	/*STEVE: define error TLE9180*/
	IfxQspi_SpiMaster_initChannelConfig(&spiChConfig, &spiMasterQspi4);

	/* set the baudrate for this channel */
	spiChConfig.base.baudrate = IFX_TLE9180_BAUDRATE;

	/* set the transfer data width */
	spiChConfig.base.mode.dataWidth = IFX_TLE9180_DATAWIDTH;

	spiChConfig.base.mode.csTrailDelay    = SpiIf_SlsoTiming_1;
	spiChConfig.base.mode.csInactiveDelay = SpiIf_SlsoTiming_7;
	spiChConfig.base.mode.shiftClock      = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;
	/*STEVE: define error TLE9180*/
	spiChConfig.sls.output.pin    = &TLE9180_SPI_CS_PIN;
	spiChConfig.sls.output.mode   = IfxPort_OutputMode_pushPull;
	spiChConfig.sls.output.driver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

	spiChConfig.channelBasedCs = IfxQspi_SpiMaster_ChannelBasedCs_enabled;

	/* initialize channel */
	IfxQspi_SpiMaster_initChannel(&Tle9180Ctrl.spiChannel, &spiChConfig);
}

/** Tle9180 configuration */
/** \brief Initialization for TLE9180
 *
 */

void PmsmFoc_Tle9180_Init(void)
{
	IfxTLE9180_Config tleConfig;

	PmsmFoc_Tle9180_InitSpiChannel();

	tleConfig.size = 8192;

	tleConfig.pins.error   = TLE9180_ERROR_PIN;
	tleConfig.pins.enable  = TLE9180_ENABLE_PIN;
	tleConfig.pins.inhibit = TLE9180_INHIBIT_PIN;
	tleConfig.pins.safeOff = TLE9180_SAFEOFF_PIN;

	tleConfig.spiChannel = &Tle9180Ctrl.spiChannel;

	/*Configure the SPI interfaces as QSPI Master Interfaces*/
	tleConfig.spiIf.spiExchange = (IfxTLE9180_SpiExchangeIfPtrType)&IfxQspi_SpiMaster_exchange;  //For TLF9180 only SPI Exchange API is required
	/* Initialize time constants for Time functions, see bsp.c */
	initTime();
	IfxTLE9180_init(&Tle9180Ctrl.driver, &tleConfig);

	/* Send startup configuration to TLE9180D */
	/* STEVE:disable? enable? */
    IfxCpu_enableInterrupts();
	IfxTLE9180_loadStartupConfiguration(&Tle9180Ctrl.driver);
    IfxCpu_disableInterrupts();
}
#endif /* End of TLE9180_DRIVER */


