/*
 * \file Dbgctrl.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "DbgCtrl.h"
#if(DBGCTRLMODE == ENABLED)

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/*******************************************************************************/
DbgCtrls g_DbgCtrl;
/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

static void DbgCtrl_StopSel(void);
static void DbgCtrl_StartSel(void);
static void DbgCtrl_SpeedSel(float32 targetspeed_arg);
static void DbgCtrl_DemoSel(void);
static void DbgCtrl_CalibrateSel(void);
/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

/* this functionis called  at periodicDebuggerTask */
#if 0
void DbgCtrl_periodic(DbgCtrls *dbgctrl_arg)
{
    if(g_motorControl.interface.CurrnetIfMode == STOP_MODE)
    {
        switch (dbgctrl_arg->eDbgCtrl_mode_usrsel)
        {
/* 2 */ case DBG_START: 
            DbgCtrl_StartSel();
            break;
/* 3 */ case DBG_CAL: 
            DbgCtrl_CalibrateSel();
            break;
/* 6 */ case DBG_DEMO: 
            DbgCtrl_DemoSel();
            break;
        default: 
            break;
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_STOP;
    }
    else if(g_motorControl.interface.CurrnetIfMode == RUNNING_MODE)
    {
        switch (dbgctrl_arg->eDbgCtrl_mode_usrsel)
        {
/* 1 */ case DBG_STOP: 
            DbgCtrl_StopSel();
            break;
/* 4 */ case DBG_SPEEDAPPLY: 
            DbgCtrl_SpeedSel(dbgctrl_arg->DbgCtrl_target_speed);
            break;
        default: 
            break;
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_START;
    }
    else if(g_motorControl.interface.CurrnetIfMode == CAL_MODE)
    {
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_CAL;
    }
    else if(g_motorControl.interface.CurrnetIfMode == DEMO_MODE)
    {
        if(dbgctrl_arg->eDbgCtrl_mode_usrsel == DBG_STOP)
        {
            DbgCtrl_StopSel();            
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_DEMO;
    }
    else if(g_motorControl.interface.CurrnetIfMode == STOPPING_MODE)
    {
        DbgCtrl_StopSel();
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_STOPPING;
    }
}
#endif
#if 1
void DbgCtrl_periodic(DbgCtrls *dbgctrl_arg, MotorControl* const motorCtrl)
{
    IFMODE CurrnetIfMode = motorCtrl->interface.CurrnetIfMode;
    switch (CurrnetIfMode)
    {
    case STOP_MODE:
        switch (dbgctrl_arg->eDbgCtrl_mode_usrsel)
        {
/* 2 */ case DBG_START: 
            DbgCtrl_StartSel();
            break;
/* 3 */ case DBG_CAL: 
            DbgCtrl_CalibrateSel();
            break;
/* 6 */ case DBG_DEMO: 
            DbgCtrl_DemoSel();
            break;
        default: 
            break;
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_STOP;    
        break;
    case RUNNING_MODE:
        switch (dbgctrl_arg->eDbgCtrl_mode_usrsel)
        {
/* 1 */ case DBG_STOP: 
            DbgCtrl_StopSel();
            break;
/* 4 */ case DBG_SPEEDAPPLY: 
            DbgCtrl_SpeedSel(dbgctrl_arg->DbgCtrl_target_speed);
            break;
        default: 
            break;
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_START;
        break;
    case CAL_MODE:
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_CAL;
        break;
    case DEMO_MODE:
        if(dbgctrl_arg->eDbgCtrl_mode_usrsel == DBG_STOP)
        {
            DbgCtrl_StopSel();            
        }
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_DEMO;
        break;
    case STOPPING_MODE:
        DbgCtrl_StopSel();
        dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_STOP;
        dbgctrl_arg->eDbgCtrl_mode_current = DBG_STOPPING;
        break;
    default:
        break;
    }
}
#endif
void DbgCtrl_init(DbgCtrls *dbgctrl_arg)
{
    /* Indicate the user select mode */
    dbgctrl_arg->eDbgCtrl_display_case[0] = D1_STOP;
    dbgctrl_arg->eDbgCtrl_display_case[1] = D2_START;
    dbgctrl_arg->eDbgCtrl_display_case[2] = D3_CAL;
    dbgctrl_arg->eDbgCtrl_display_case[3] = D4_SPEEDAPPLY;
    dbgctrl_arg->eDbgCtrl_display_case[4] = D5_DEMO;

    dbgctrl_arg->eDbgCtrl_mode_usrsel  = DBG_READY;
    dbgctrl_arg->eDbgCtrl_mode_current = DBG_READY;
    dbgctrl_arg->DbgCtrl_target_speed  = 1000;
}

static void DbgCtrl_CalibrateSel(void)
{
    /* Go to StateMachine_PhaseCalibration */
    PmsmFoc_Interface_calMotor(&g_motorControl);
}

static void DbgCtrl_StartSel(void)
{
    /* Go to StateMachine_focClosedLoop or StateMachine_PhaseCalibration */
    PmsmFoc_Interface_startMotor(&g_motorControl);
}

static void DbgCtrl_StopSel(void)
{
    /* Go to StateMachine_motorStop */
    PmsmFoc_Interface_stopMotor(&g_motorControl);
}

static void DbgCtrl_SpeedSel(float32 targetspeed_arg)
{
    PmsmFoc_Interface_setMotorTargetSpeed(&g_motorControl, targetspeed_arg);
}

static void DbgCtrl_DemoSel(void)
{
    PmsmFoc_Interface_setDemo(&g_motorControl);
}
#endif /* End of DBGCTRL*/
