/*
 * \file Dbgctrl.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "DbgCtrl.h"
#if(DBGCTRLMODE == ENABLED)

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/*******************************************************************************/
DBGCTRL_S g_DbgCtrl;
/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/

static void DbgCtrl_CalibrateSel(void);
static void DbgCtrl_StartSel(void);
static void DbgCtrl_StopSel(void);
static void DbgCtrl_SpeedSel(float32 targetspeedArg);
static void DbgCtrl_DemoSel(void);
static void DbgCtrl_OpenloopSel(void);
/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/

/* this functionis called  at periodicDebuggerTask */
void DbgCtrl_periodic(DBGCTRL_S *dbgArg, MOTORCTRL_S* const motorCtrl)
{
    IFMODE_E CurrnetIfMode = motorCtrl->interface.CurrnetIfMode;
    switch (CurrnetIfMode)
    {
    case STOP_MODE: 
        switch (dbgArg->Dbg_eUsrMode)
        {
/* 2 */ case DBG_START: 
            DbgCtrl_StartSel();
            break;
/* 3 */ case DBG_CAL: 
            DbgCtrl_CalibrateSel();
            break;
/* 5 */ case DBG_DEMO: 
            DbgCtrl_DemoSel();
            break;
/* 6 */ case DBG_OPENLOOP: 
            DbgCtrl_OpenloopSel();
            break;
        default: 
            break;
        }
        dbgArg->Dbg_eUsrMode = DBG_READY;
        dbgArg->Dbg_eCurMode = DBG_STOP;
        break;
    case RUNNING_MODE: 
        switch (dbgArg->Dbg_eUsrMode)
        {
/* 1 */ case DBG_STOP: 
            DbgCtrl_StopSel();
            break;
/* 4 */ case DBG_SPEEDAPPLY: 
            DbgCtrl_SpeedSel(dbgArg->Dbg_TargetSpeed);
            break;
        default: 
            break;
        }
        dbgArg->Dbg_eUsrMode = DBG_READY;
        dbgArg->Dbg_eCurMode = DBG_START;
        break;
    case CAL_MODE: 
        dbgArg->Dbg_eUsrMode = DBG_READY;
        dbgArg->Dbg_eCurMode = DBG_CAL;
        break;
    case DEMO_MODE: 
        if(dbgArg->Dbg_eUsrMode == DBG_STOP)
        {
            DbgCtrl_StopSel();            
        }
        dbgArg->Dbg_eUsrMode = DBG_READY;
        dbgArg->Dbg_eCurMode = DBG_DEMO;
        break;
    case STOPPING_MODE: 
        DbgCtrl_StopSel();
        dbgArg->Dbg_eUsrMode = DBG_STOP;
        dbgArg->Dbg_eCurMode = DBG_STOPPING;
        break;
    default: 
        break;
    }
}

void DbgCtrl_init(DBGCTRL_S *dbgArg)
{
    /* Indicate the user select mode */
    dbgArg->Dbg_eDispMode[0] = D1_STOP;
    dbgArg->Dbg_eDispMode[1] = D2_START;
    dbgArg->Dbg_eDispMode[2] = D3_CAL;
    dbgArg->Dbg_eDispMode[3] = D4_SPEEDAPPLY;
    dbgArg->Dbg_eDispMode[4] = D5_DEMO;
    dbgArg->Dbg_eDispMode[5] = D6_OPENLOOP;

    dbgArg->Dbg_eUsrMode    = DBG_READY;
    dbgArg->Dbg_eCurMode    = DBG_READY;
    dbgArg->Dbg_TargetSpeed = 1000;
}

static void DbgCtrl_CalibrateSel(void)
{
    /* Go to STATE_PhaseCalibration */
    PmsmFoc_Interface_calMotor(&g_motorCtrl);
}

static void DbgCtrl_StartSel(void)
{
    /* Go to STATE_focClosedLoop or STATE_PhaseCalibration */
    PmsmFoc_Interface_startMotor(&g_motorCtrl);
}

static void DbgCtrl_StopSel(void)
{
    /* Go to STATE_motorStop */
    PmsmFoc_Interface_stopMotor(&g_motorCtrl);
}

static void DbgCtrl_SpeedSel(float32 targetspeedArg)
{
    PmsmFoc_Interface_setMotorTargetSpeed(&g_motorCtrl, targetspeedArg);
}

static void DbgCtrl_DemoSel(void)
{
    #if(FOC_CONTROL_SCHEME == SPEED_CONTROL)
    PmsmFoc_Interface_setDemo(&g_motorCtrl);
    #endif
}

static void DbgCtrl_OpenloopSel(void)
{
    /* Go to STATE_Openloop*/
    PmsmFoc_Interface_setOpenlooptest(&g_motorCtrl);
}
#endif