/*
 * \file Ifx_ShellBb.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#include "Ifx_ShellBb.h"

boolean Ifx_ShellBb_init(Ifx_ShellBb* bb, Ifx_Shell* shell, SyncProtocol* protocol, SyncProtocol_Port localPort, SyncProtocol_Port remotePort, Ifx_SizeT rxBufferSize, Ifx_SizeT txBufferSize)
{
    bb->_shell                  = shell;
    Ifx_FifoDPipe_init(&bb->_dPipe, rxBufferSize, txBufferSize);

    return SyncProtocol_addClient(protocol, &bb->_bbClient, localPort, remotePort, bb->_bbClientMessagePayloadRx, sizeof(bb->_bbClientMessagePayloadRx));
}

void Ifx_ShellBb_processMessages(Ifx_ShellBb* bb)
{
//    if (bb->_shell == NULL)

    if (bb->_shell == NULL_PTR)
    {   /* BB un-initialized */
        return;
    }

    /* Process received */
    if (bb->_bbClient.receive.messageValid)
    {
        SyncProtocol_MessageId id;
        uint32                 length;
        uint8*                 payloadRx;

        if (SyncProtocol_getReadMessageBuffer(&bb->_bbClient, &id, &payloadRx, &length))
        {
            switch (id)
            {
            case SYNCPROTOCOL_MESSAGE_ID_RAWBUFFER:
            {
            	Ifx_Fifo_write(bb->_dPipe.rx, payloadRx, length, IFX_CFG_SHELL_TIMEOUT);
            }
            break;
            }

            SyncProtocol_releaseReadMessageBuffer(&bb->_bbClient);
        }
    }

    /* Process data to be send */
    if (SyncProtocol_isSendBusy(&bb->_bbClient))
    {
        return;
    }


    if (Ifx_Fifo_isEmpty(bb->_dPipe.tx) == FALSE)
    {
        uint32                 length;
        uint8* payloadTx = bb->_bbClientMessagePayloadTx;

        length = Ifx_Fifo_readCount(bb->_dPipe.tx);
        length = length > sizeof(bb->_bbClientMessagePayloadTx) ? sizeof(bb->_bbClientMessagePayloadTx) : length;

        length = length > 200 ? 200 : length; /* FIXME Checksum error if payload length is not limited. Check root cause. Check SYNCPROTOCOL_FRAME_PAYLOAD_MAX_LENGTH, SYNCPROTOCOL_MESSAGE_PAYLOAD_MAX_LENGTH */


        if (SyncProtocol_setSendMessageBuffer(
                &bb->_bbClient,
                SYNCPROTOCOL_MESSAGE_ID_RAWBUFFER,
                bb->_bbClientMessagePayloadTx,
                length))
        {
            Ifx_Fifo_read(bb->_dPipe.tx, payloadTx, length, TIME_NULL);
            SyncProtocol_sendMessage(&bb->_bbClient);
        }
    }
}
