/**
 * \file Ifx_FifoDPipe.c
 * \brief FIFO DPipe
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#include "Ifx_FifoDPipe.h"
#include "_Utilities/Ifx_Assert.h"
#include <string.h>
#include <stdio.h>

void Ifx_FifoDPipe_init(Ifx_FifoDPipe* dPipe, Ifx_SizeT rxBufferSize, Ifx_SizeT txBufferSize)
{
    if ((rxBufferSize != 0) && (txBufferSize != 0))
    {
        dPipe->rx = Ifx_Fifo_create(rxBufferSize, 1);
        dPipe->tx = Ifx_Fifo_create(txBufferSize, 1);
    }
    else
    {
        dPipe->rx = NULL_PTR;
        dPipe->tx = NULL_PTR;
    }

    Ifx_FifoDPipe_initStdIf(dPipe);
}


void Ifx_FifoDPipe_deInit(Ifx_FifoDPipe* dPipe)
{
    if (dPipe->rx)
    {
        Ifx_Fifo_destroy(dPipe->rx);
        dPipe->rx = NULL_PTR;
    }

    if (dPipe->tx)
    {
        Ifx_Fifo_destroy(dPipe->tx);
        dPipe->tx = NULL_PTR;
    }
}


boolean Ifx_FifoDPipe_write(Ifx_FifoDPipe* dPipe, void* data, Ifx_SizeT* count)
{
    Ifx_SizeT left;
    boolean   result = TRUE;

    if ((*count != 0) && !Ifx_FifoDPipe_isTxDisabled(dPipe))
    {
        left    = Ifx_Fifo_write(dPipe->tx, data, *count, Ifx_FifoDPipe_getWriteTimeout(dPipe));

        *count -= left;
        result  = left == 0;
    }

    return result;
}


void Ifx_FifoDPipe_writeFormatted(Ifx_FifoDPipe* dPipe, pchar format, ...)
{
    char      message[255 + 1];
    Ifx_SizeT count;
    va_list   args;
    va_start(args, format);
    vsnprintf((char*)message, sizeof(message), format, args);
    va_end(args);
    count = (Ifx_SizeT)strlen(message);
    Ifx_FifoDPipe_write(dPipe, (void*)message, &count);
}


void Ifx_FifoDPipe_writeText(Ifx_FifoDPipe* dPipe, pchar text)
{
    Ifx_SizeT count;
    count = (Ifx_SizeT)strlen(text);
    Ifx_FifoDPipe_write(dPipe, (void*)text, &count);
}


boolean Ifx_FifoDPipe_read(Ifx_FifoDPipe* dPipe, void* data, Ifx_SizeT* count, Ifx_TickTime timeout)
{
    Ifx_SizeT left = Ifx_Fifo_read(dPipe->rx, data, *count, timeout);

    *count -= left;

    return left == 0;
}


sint32 Ifx_FifoDPipe_getReadCount(Ifx_FifoDPipe* dPipe)
{
    return Ifx_Fifo_readCount(dPipe->rx);
}


IfxStdIf_DPipe_ReadEvent Ifx_FifoDPipe_getReadEvent(Ifx_FifoDPipe* dPipe)
{
    return &dPipe->rx->eventWriter;
}


sint32 Ifx_FifoDPipe_getWriteCount(Ifx_FifoDPipe* dPipe)
{
    return Ifx_Fifo_writeCount(dPipe->tx);
}


IfxStdIf_DPipe_WriteEvent Ifx_FifoDPipe_getWriteEvent(Ifx_FifoDPipe* dPipe)
{
    return &dPipe->tx->eventWriter;
}


boolean Ifx_FifoDPipe_canReadCount(Ifx_FifoDPipe* dPipe, Ifx_SizeT count, Ifx_TickTime timeout)
{
    return Ifx_Fifo_canReadCount(dPipe->rx, count, timeout);
}


boolean Ifx_FifoDPipe_canWriteCount(Ifx_FifoDPipe* dPipe, Ifx_SizeT count, Ifx_TickTime timeout)
{
    return Ifx_Fifo_canWriteCount(dPipe->tx, count, timeout);
}


boolean Ifx_FifoDPipe_flushTx(Ifx_FifoDPipe* dPipe, Ifx_TickTime timeout)
{
    return Ifx_Fifo_flush(dPipe->tx, timeout);
}


void Ifx_FifoDPipe_clearRx(Ifx_FifoDPipe* dPipe)
{
    Ifx_Fifo_clear(dPipe->rx);
}


void Ifx_FifoDPipe_clearTx(Ifx_FifoDPipe* dPipe)
{
    Ifx_Fifo_clear(dPipe->tx);
}


boolean Ifx_FifoDPipe_initStdIf(Ifx_FifoDPipe* dPipe)
{
    IfxStdIf_DPipe_initStdIf(&dPipe->stdif);

    /* Set the API link */
    dPipe->stdif.driver         = dPipe;
    dPipe->stdif.write          = (IfxStdIf_DPipe_Write) & Ifx_FifoDPipe_write;
    dPipe->stdif.read           = (IfxStdIf_DPipe_Read) & Ifx_FifoDPipe_read;
    dPipe->stdif.getReadCount   = (IfxStdIf_DPipe_GetReadCount) & Ifx_FifoDPipe_getReadCount;
    dPipe->stdif.getReadEvent   = (IfxStdIf_DPipe_GetReadEvent) & Ifx_FifoDPipe_getReadEvent;
    dPipe->stdif.getWriteCount  = (IfxStdIf_DPipe_GetWriteCount) & Ifx_FifoDPipe_getWriteCount;
    dPipe->stdif.getWriteEvent  = (IfxStdIf_DPipe_GetWriteEvent) & Ifx_FifoDPipe_getWriteEvent;
    dPipe->stdif.canReadCount   = (IfxStdIf_DPipe_CanReadCount) & Ifx_FifoDPipe_canReadCount;
    dPipe->stdif.canWriteCount  = (IfxStdIf_DPipe_CanWriteCount) & Ifx_FifoDPipe_canWriteCount;
    dPipe->stdif.flushTx        = (IfxStdIf_DPipe_FlushTx) & Ifx_FifoDPipe_flushTx;
    dPipe->stdif.clearTx        = (IfxStdIf_DPipe_ClearTx) & Ifx_FifoDPipe_clearTx;
    dPipe->stdif.clearRx        = (IfxStdIf_DPipe_ClearRx) & Ifx_FifoDPipe_clearRx;
    dPipe->stdif.onReceive      = (IfxStdIf_DPipe_OnReceive) & Ifx_FifoDPipe_onReceive;
    dPipe->stdif.onTransmit     = (IfxStdIf_DPipe_OnTransmit) & Ifx_FifoDPipe_onTransmit;
    dPipe->stdif.onError        = (IfxStdIf_DPipe_OnError) & Ifx_FifoDPipe_onError;
    dPipe->stdif.getSendCount   = (IfxStdIf_DPipe_GetSendCount) & Ifx_FifoDPipe_getSendCount;
    dPipe->stdif.getTxTimeStamp = (IfxStdIf_DPipe_GetTxTimeStamp) & Ifx_FifoDPipe_getTxTimeStamp;
    dPipe->stdif.resetSendCount = (IfxStdIf_DPipe_ResetSendCount) & Ifx_FifoDPipe_resetSendCount;
    dPipe->stdif.txDisabled     = FALSE;
    return TRUE;
}
