/*
 * \file Display_Cfg_AppKitTft_TC387A.h
 * \brief
 * \ingroup display_configuration
 * \version
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_
#define DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_
/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include <IfxSrc_reg.h>
#include <_PinMap/IfxQspi_PinMap.h>
#include <_PinMap/IfxPort_PinMap.h>

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/* set here the used pins for TFT and TOUCH (QSPI0) */
#define TFT_MAX_BAUDRATE            50000000  // maximum baudrate which is possible to get a small time quantum
#define TFT_SCLK_PIN	            IfxQspi0_SCLK_P20_13_OUT
#define TFT_MTSR_PIN	            IfxQspi0_MTSR_P20_14_OUT
#define TFT_MRST_PIN	            IfxQspi0_MRSTA_P20_12_IN
#define TFT_USE_DMA  				// comment line for not using DMA
#define DMA_CH_TFT_TX               TFT_DMA_CH_TXBUFF_TO_TXFIFO
#define DMA_CH_TFT_RX               TFT_DMA_CH_RXBUFF_FROM_RXFIFO
#define TFT_TRANSMIT_CALLBACK       tft_transmit_callback

#define TFT_USE_CHIPSELECT          IfxQspi0_SLSO8_P20_6_OUT
#define TFT_UPDATE_IRQ              MODULE_SRC.GPSR.GPSR[0].SR[0]

#define TOUCH_USE_CHIPSELECT        IfxQspi0_SLSO9_P20_3_OUT
#define TOUCH_USE_INT               IfxPort_P20_9

/* define the CPU which service the selected peripherals */
#define CPU_WHICH_SERVICE_TFT          0     /**< \brief Define the CPU which service the Tft and touch where functions/variables are located.  */

/* define the CPU which holds the DAS variables */
#define DAS_VAR_LOCATION            1

//#define TFT_OVER_DAS

#define REFRESH_TFT 50		// Refresh rate [ms]; 1x refresh ~0,8 % CPU load; for graphic-out: 4 colors ~ 1.2 % CPU load, 16 colors ~ 0.8 % CPU load
							// Max refresh rate ~ 40 ms due to QSPI-load


/**
 * \name Interrupt priority configuration for CPU.
 * The interrupt priority range is [1,255]
 * \{
 */
#define ISR_PRIORITY_CPUSRV0        2  /**< \brief Define the conio periodic interrupt priority must be lower than QSPIx priorities.  */
#define ISR_PRIORITY_TFT_QSPI_ER    42  /**< \brief Define the TFT error interrupt priority.  */
#define ISR_PRIORITY_BACKLIGHT      30  /**< \brief Define the TOMx_x compare match interrupt priority.  */
#define ISR_PRIORITY_TFT_QSPI_TX    40  /**< \brief Define the TFT transmit interrupt priority.  */
#define ISR_PRIORITY_TFT_QSPI_RX    41  /**< \brief Define the TFT receive interrupt priority.  */

/**
 * \name DMA channel configuration.
 * \{
 */

#define TFT_DMA_CH_TXBUFF_TO_TXFIFO        0 /**< \brief Dma channel used for TFT Master Qspi Transmit  */
#define TFT_DMA_CH_RXBUFF_FROM_RXFIFO      1 /**< \brief Dma channel used for TFT Master Qspi Receive  */




/**
 * \name DMA channel configuration.
 * \{
 */

#define TFT_DMA_CH_TXBUFF_TO_TXFIFO        0 /**< \brief Dma channel used for TFT Master Qspi Transmit  */
#define TFT_DMA_CH_RXBUFF_FROM_RXFIFO      1 /**< \brief Dma channel used for TFT Master Qspi Receive  */

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/

#endif /* DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_ */
